name: Lint and Test

on:
  push:
    branches:
      - main
      - task-* # Runs on branches like task-1, task-2, etc.
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run Code Linting
        run: flake8 scripts/ notebooks/

      # Optional: If you have tests
      - name: Run Tests (Optional)
        run: |
          pip install pytest
          pytest tests/
